import { parseNetworkPattern } from '../patterns.js';
import type {
  CodexCompilation,
  CompilationGap,
  FileRule,
  LoadedPolicy,
  NetworkRule
} from '../types.js';

export const MINIMUM_CODEX_VERSION = '0.138.0';

export function compileCodexPermissionProfile(policy: LoadedPolicy): CodexCompilation {
  const gaps: CompilationGap[] = [];
  const filesystem = new Map<string, 'read' | 'write' | 'deny'>();
  if ((policy.document.defaults?.files ?? 'allow') === 'deny') {
    filesystem.set('.', 'deny');
    gaps.push({
      resource: 'file',
      ruleId: null,
      severity: 'error',
      message: 'A file default-deny is compiled conservatively as a denied workspace root, but allow carve-outs require platform conformance testing.'
    });
  } else filesystem.set('.', 'write');

  for (const rule of policy.document.rules?.files ?? []) {
    compileFileRule(rule, filesystem, gaps);
  }

  const domains = new Map<string, 'allow' | 'deny'>();
  const networkDefault = policy.document.defaults?.network ?? 'allow';
  if (networkDefault === 'allow') {
    domains.set('*', 'allow');
    gaps.push({
      resource: 'network',
      ruleId: null,
      severity: 'error',
      message: 'Codex permission profiles block loopback, link-local, and private destinations by default, so portable network default-allow is compiled more restrictively.'
    });
  }
  for (const rule of policy.document.rules?.network ?? []) compileNetworkRule(rule, domains, gaps);
  const networkEnabled = [...domains.values()].includes('allow');

  if ((policy.document.defaults?.environment ?? 'allow') === 'deny') {
    gaps.push({
      resource: 'environment',
      ruleId: null,
      severity: 'error',
      message: 'Codex permission profiles cannot represent a default-deny environment policy; use a filtered launcher.'
    });
  }
  for (const rule of policy.document.rules?.environment ?? []) {
    gaps.push({
      resource: 'environment',
      ruleId: rule.id,
      severity: 'error',
      message: 'Codex permission profiles do not filter inherited environment variables; use a filtered launcher.'
    });
  }
  if ((policy.document.defaults?.strings ?? 'allow') === 'deny') {
    gaps.push({
      resource: 'string',
      ruleId: null,
      severity: 'error',
      message: 'Codex permission profiles cannot represent a default-deny string policy.'
    });
  }
  for (const rule of policy.document.rules?.strings ?? []) {
    gaps.push({
      resource: 'string',
      ruleId: rule.id,
      severity: 'error',
      message: 'String mediation requires in-process boundary filtering; Codex hooks have incomplete tool coverage.'
    });
  }

  const lines = [
    '# Generated by aiignore. Review compilation gaps before use.',
    `# policy-sha256: ${policy.digest}`,
    `# minimum-codex-version: ${MINIMUM_CODEX_VERSION}`,
    'default_permissions = "aiignore"',
    '',
    '[permissions.aiignore.filesystem]',
    'glob_scan_max_depth = 16',
    '":minimal" = "read"',
    '',
    '[permissions.aiignore.filesystem.":workspace_roots"]'
  ];
  for (const [pattern, access] of filesystem) lines.push(`${tomlString(pattern)} = ${tomlString(access)}`);

  lines.push('', '[permissions.aiignore.network]', `enabled = ${networkEnabled ? 'true' : 'false'}`);
  if (networkEnabled) {
    lines.push('mode = "limited"', 'allow_local_binding = false');
  }
  if (networkEnabled && domains.size > 0) {
    lines.push('', '[permissions.aiignore.network.domains]');
    for (const [domain, effect] of domains) lines.push(`${tomlString(domain)} = ${tomlString(effect)}`);
  }
  if (gaps.length > 0) {
    lines.push('', '# Compilation gaps:');
    for (const gap of gaps) {
      lines.push(`# [${gap.severity}] ${gap.resource}/${gap.ruleId ?? 'default'}: ${gap.message}`);
    }
  }

  return {
    format: 'codex-permission-profile-v1',
    policyDigest: policy.digest,
    minimumCodexVersion: MINIMUM_CODEX_VERSION,
    toml: `${lines.join('\n')}\n`,
    gaps,
    exact: gaps.length === 0
  };
}

function compileFileRule(
  rule: FileRule,
  output: Map<string, 'read' | 'write' | 'deny'>,
  gaps: CompilationGap[]
): void {
  const operations = rule.operations ?? ['discover', 'index', 'read', 'write', 'execute'];
  let access: 'read' | 'write' | 'deny' | undefined;
  if (rule.effect === 'deny') access = 'deny';
  else if (rule.effect === 'read-only') access = 'read';
  else if (rule.effect === 'allow') access = 'write';

  if (rule.effect === 'audit') {
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'warning',
      message: 'Audit-only file rules are not represented in a Codex permission profile.'
    });
    return;
  }
  if (operations.length !== 5) {
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'error',
      message: `Codex filesystem permissions cannot exactly represent operation subset: ${operations.join(', ')}.`
    });
  }
  if (rule.effect === 'read-only' || rule.effect === 'allow') {
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'warning',
      message: 'Portable Codex enforcement of read/write glob grants is weaker than exact-path grants.'
    });
  }
  if (access) {
    for (const pattern of rule.paths) {
      const portablePattern = stripLeadingSlash(pattern);
      const compiledPattern =
        access === 'deny'
          ? deniedFilesystemTarget(portablePattern)
          : { target: portablePattern, glob: false };
      mergeConservative(output, compiledPattern.target, access);
      if (access === 'deny' && compiledPattern.glob && operations.some((operation) => operation !== 'read')) {
        gaps.push({
          resource: 'file',
          ruleId: rule.id,
          severity: 'error',
          message: `Codex deny glob ${pattern} cannot enforce ${operations.filter((operation) => operation !== 'read').join(', ')}; deny globs are read-focused.`
        });
      }
    }
  }
  for (const exception of rule.except ?? []) {
    mergeConservative(output, stripLeadingSlash(exception), 'write');
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'warning',
      message: `Exception ${exception} compiles as a write glob and requires platform conformance testing.`
    });
  }
}

function compileNetworkRule(
  rule: NetworkRule,
  output: Map<string, 'allow' | 'deny'>,
  gaps: CompilationGap[]
): void {
  if (rule.effect === 'audit') {
    gaps.push({
      resource: 'network',
      ruleId: rule.id,
      severity: 'warning',
      message: 'Audit-only network rules are not represented in a Codex permission profile.'
    });
    return;
  }
  for (const url of rule.urls) {
    const parsed = parseNetworkPattern(url, `${rule.id}.urls`);
    const domain =
      parsed.hostnameMode === 'exact'
        ? parsed.hostname
        : `${parsed.hostnameMode === 'subdomains' ? '*' : '**'}.${parsed.hostname}`;
    mergeNetworkConservative(output, domain, rule.effect);
    if (parsed.pathname !== '/**' || parsed.port !== '') {
      gaps.push({
        resource: 'network',
        ruleId: rule.id,
        severity: 'error',
        message: `Codex domain policy broadens ${url}; scheme, port, and path are not represented.`
      });
    }
    gaps.push({
      resource: 'network',
      ruleId: rule.id,
      severity: 'warning',
      message: `Codex domain policy does not preserve the ${parsed.scheme} scheme constraint for ${url}.`
    });
  }
  for (const exception of rule.except ?? []) {
    gaps.push({
      resource: 'network',
      ruleId: rule.id,
      severity: 'error',
      message: `Network exception ${exception} cannot be compiled without changing ordered-rule semantics.`
    });
  }
}

function mergeConservative(
  map: Map<string, 'read' | 'write' | 'deny'>,
  pattern: string,
  access: 'read' | 'write' | 'deny'
): void {
  const rank = { read: 1, write: 2, deny: 3 } as const;
  const current = map.get(pattern);
  if (!current || rank[access] > rank[current]) map.set(pattern, access);
}

function mergeNetworkConservative(
  map: Map<string, 'allow' | 'deny'>,
  domain: string,
  effect: 'allow' | 'deny'
): void {
  if (effect === 'deny' || !map.has(domain)) map.set(domain, effect);
}

function stripLeadingSlash(pattern: string): string {
  return pattern.startsWith('/') ? pattern.slice(1) : pattern;
}

function deniedFilesystemTarget(pattern: string): { target: string; glob: boolean } {
  const subtree = /^(.*)\/\*\*$/u.exec(pattern);
  if (subtree) {
    const prefix = subtree[1] ?? '';
    if (prefix && !/[*?[]/u.test(prefix)) return { target: prefix, glob: false };
  }
  return { target: pattern, glob: /[*?[]/u.test(pattern) };
}

function tomlString(value: string): string {
  return JSON.stringify(value);
}
