import { PolicyEngine } from '../engine.js';
import { FILE_OPERATIONS } from '../types.js';
import type {
  CompilationGap,
  EnvironmentRule,
  FileRule,
  GeminiCompilation,
  LoadedPolicy
} from '../types.js';

export const GEMINI_IGNORE_FILE = '.aiignore.generated.geminiignore';

interface OrderedFileRule {
  rule: FileRule;
  index: number;
}

export function compileGeminiConfiguration(policy: LoadedPolicy): GeminiCompilation {
  const gaps: CompilationGap[] = [];
  const ignoreLines = [
    '# Generated by aiignore for Gemini CLI context filtering.',
    `# policy-sha256: ${policy.digest}`,
    '# This is not a filesystem sandbox; retain the BeforeTool hook.',
    ''
  ];

  if ((policy.document.defaults?.files ?? 'allow') === 'deny') {
    ignoreLines.push('/**');
    gaps.push({
      resource: 'file',
      ruleId: null,
      severity: 'error',
      message: 'Gemini ignore files represent default-deny context filtering, but not the default-deny read, write, or execute operations; use the BeforeTool hook and sandbox.'
    });
  }

  const orderedRules = (policy.document.rules?.files ?? [])
    .map((rule, index): OrderedFileRule => ({ rule, index }))
    .sort(compareFileRules);
  for (const { rule } of orderedRules) compileFileRule(rule, ignoreLines, gaps);

  const allowed = new Set<string>();
  const blocked = new Set<string>();
  if ((policy.document.defaults?.environment ?? 'allow') === 'deny') {
    gaps.push({
      resource: 'environment',
      ruleId: null,
      severity: 'error',
      message: 'Gemini environment redaction cannot represent a default-deny environment policy; use aiignore run.'
    });
  }
  for (const rule of policy.document.rules?.environment ?? []) {
    compileEnvironmentRule(rule, gaps);
  }
  const engine = new PolicyEngine(policy);
  const exactEnvironmentNames = new Set(
    (policy.document.rules?.environment ?? []).flatMap((rule) =>
      rule.names.filter((name) => !hasGlob(name))
    )
  );
  for (const name of exactEnvironmentNames) {
    const decision = engine.decideEnvironment(name, false);
    if (['deny', 'drop', 'redact'].includes(decision.effect)) blocked.add(name);
    else allowed.add(name);
  }

  for (const rule of policy.document.rules?.network ?? []) {
    gaps.push({
      resource: 'network',
      ruleId: rule.id,
      severity: 'error',
      message: 'Gemini context settings do not enforce URL policy; use the BeforeTool hook plus an enabled sandbox or proxy.'
    });
  }
  if ((policy.document.defaults?.network ?? 'allow') === 'deny') {
    gaps.push({
      resource: 'network',
      ruleId: null,
      severity: 'error',
      message: 'Gemini network default-deny requires sandbox network controls; it is not represented by this generated context configuration.'
    });
  }
  for (const rule of policy.document.rules?.strings ?? []) {
    gaps.push({
      resource: 'string',
      ruleId: rule.id,
      severity: 'error',
      message: 'Gemini context settings cannot mediate arbitrary string boundaries; the BeforeTool hook covers tool input only.'
    });
  }
  if ((policy.document.defaults?.strings ?? 'allow') === 'deny') {
    gaps.push({
      resource: 'string',
      ruleId: null,
      severity: 'error',
      message: 'Gemini context settings cannot represent a default-deny string policy.'
    });
  }

  const settings: GeminiCompilation['settings'] = {
    context: {
      fileFiltering: { customIgnoreFilePaths: [GEMINI_IGNORE_FILE] }
    },
    security: {
      environmentVariableRedaction: {
        enabled: blocked.size > 0,
        allowed: [...allowed].sort(),
        blocked: [...blocked].sort()
      }
    }
  };

  return {
    format: 'gemini-cli-adapter-v1',
    policyDigest: policy.digest,
    ignoreFileName: GEMINI_IGNORE_FILE,
    ignoreFile: `${ignoreLines.join('\n').replace(/\n+$/u, '')}\n`,
    settings,
    gaps,
    exact: gaps.length === 0
  };
}

function compileFileRule(rule: FileRule, output: string[], gaps: CompilationGap[]): void {
  const operations = rule.operations ?? [...FILE_OPERATIONS];
  const contextOperations = operations.filter((operation) =>
    ['discover', 'index'].includes(operation)
  );
  const directOperations = operations.filter((operation) =>
    ['read', 'write', 'execute'].includes(operation)
  );

  if (directOperations.length > 0) {
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'error',
      message: `Gemini ignore files do not mediate direct ${directOperations.join(', ')} operations; use the BeforeTool hook and sandbox.`
    });
  }
  if (contextOperations.length === 1) {
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'error',
      message: `Gemini ignore files cannot distinguish ${contextOperations[0]} from the other context operation.`
    });
  }
  if (rule.except && rule.except.length > 0) {
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'error',
      message: 'Rule-local exceptions cannot preserve fallback to lower-priority Gemini ignore rules.'
    });
  }
  if (contextOperations.length === 0) return;
  if (rule.effect === 'audit') {
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'warning',
      message: 'Audit-only context rules are not represented in a Gemini ignore file.'
    });
    return;
  }

  const prefix = rule.effect === 'deny' ? '' : '!';
  if (prefix === '!') {
    gaps.push({
      resource: 'file',
      ruleId: rule.id,
      severity: 'error',
      message: 'Gemini ignore negation cannot reliably re-include content below an already ignored parent directory.'
    });
  }
  for (const pattern of rule.paths) output.push(`${prefix}${geminiPattern(pattern)}`);
  for (const exception of rule.except ?? []) output.push(`!${geminiPattern(exception)}`);
}

function compileEnvironmentRule(rule: EnvironmentRule, gaps: CompilationGap[]): void {
  if (rule.except && rule.except.length > 0) {
    gaps.push({
      resource: 'environment',
      ruleId: rule.id,
      severity: 'error',
      message: 'Gemini environment redaction has no rule-local exception semantics.'
    });
  }
  if (rule.effect === 'audit') {
    gaps.push({
      resource: 'environment',
      ruleId: rule.id,
      severity: 'warning',
      message: 'Audit-only environment rules are not represented in Gemini settings.'
    });
    return;
  }
  for (const name of rule.names) {
    if (hasGlob(name)) {
      gaps.push({
        resource: 'environment',
        ruleId: rule.id,
        severity: 'error',
        message: `Gemini environment redaction accepts variable names, not portable aiignore glob ${name}.`
      });
      continue;
    }
  }
  if (rule.effect !== 'allow') {
    gaps.push({
      resource: 'environment',
      ruleId: rule.id,
      severity: 'error',
      message: `Gemini redaction does not implement aiignore ${rule.effect} lifecycle semantics or custom replacement values; use aiignore run.`
    });
  }
}

function compareFileRules(left: OrderedFileRule, right: OrderedFileRule): number {
  const priority = (left.rule.priority ?? 0) - (right.rule.priority ?? 0);
  return priority === 0 ? left.index - right.index : priority;
}

function geminiPattern(pattern: string): string {
  const normalized = pattern.startsWith('/') ? pattern : `/${pattern}`;
  return normalized.endsWith('/') ? `${normalized}**` : normalized;
}

function hasGlob(name: string): boolean {
  return /[*?[\]]/u.test(name);
}
